name: Layotto Env Pipeline 🌊

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    name: "🍀 DeadLink Validation"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install markdown-link-check
        run: sudo npm install -g markdown-link-check@3

      - name: Install and start docsify server
        run: |
             sudo npm i docsify-cli -g
             nohup docsify serve docs -p 3000 &

      - name: Check dead links in all the .md files
        run: make style.deadlink  
